# Generated by Django 5.1.3 on 2024-12-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('Qualification', models.CharField(max_length=32)),
                ('Gender', models.CharField(max_length=10)),
                ('YOP', models.IntegerField(max_length=4)),
                ('Age', models.IntegerField(max_length=2)),
                ('Skills', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('Mock_Rating', models.IntegerField(max_length=2)),
                ('Company', models.CharField(max_length=10)),
            ],
        ),
    ]
