# Generated by Django 5.1.3 on 2024-12-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Mock_Rating',
            field=models.IntegerField(max_length=5),
        ),
    ]
