# Generated by Django 5.1.3 on 2024-12-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0003_alter_student_gender_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Age',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Skills',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='YOP',
            field=models.IntegerField(max_length=10),
        ),
    ]
