# Generated by Django 5.1.3 on 2024-12-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0005_alter_student_age_alter_student_mock_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Mock_Rating',
            field=models.CharField(max_length=10),
        ),
    ]
